#include<stdio.h>
//simple calculator 
int main()
{
	int a, b; //declaration of the variables...
	printf("Enter Number 1 :"); // asking for input from the user...
	scanf("%d", &a); //importing the input to variable a...
	
	printf("Enter Number 2 :"); //asking for input from the user...
	scanf("%d", &b); //importing the input to variable b...
	
	printf("Addition : %d", a+b); //addition... 
	printf("\nSubstraction : %d", a-b); //subsrtaction..
	printf("\nMultiplication : %d", a*b); //multiplication...
	printf("\nDivision : %d", a/b); //division...
	printf("\nmodulo : %d", a%b); //modlus.. 
	
	return 0;
}
